### ISSUE TITLE
js is broken

### ISSUE THREAD

**Issue by ninjasort** [colophonemes/metalsmith-uncss#5]
uncss is hacking my dynamic styles and they don't work. Any ideas?

**Comment by colophonemes** [comment]
Sorry, can you give more detail? Not sure what you mean by 'dynamic
styles'. Do you mean classes added by JavaScript after page load?

If so, have a look at the UnCSS documentation about ignoring classes. You
can pass options to the UnCSS module using the `uncss` key in the options
hash.

**Comment by ninjasort** [comment]
Yep. did that. What if there are 200+ classes getting added dynamically? Do I add a 200+ item array?

**Comment by colophonemes** [comment]
I mean, I guess so. This is more of a question about how UnCSS works, rather than the metalsmith wrapper. Alternatively, run UnCSS on your base styles (e.g. Bootstrap framework etc.) and build a separate stylesheet which has the dynamic style definitions in it, then use something like [metalsmith-concat](https://www.npmjs.com/package/metalsmith-concat) to concatenate them afterwards.

**Comment by ninjasort** [comment]
Okay, thanks.
